"""Render a Chart model to LilyPond source using the roi.ily style include."""
from __future__ import annotations

from fractions import Fraction

from .model import Chart, _DURATIONS, chord_token, _duration_token, _split_bar


def _ly_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _chord_line(chart: Chart) -> str:
    """ChordNames voice: expanded chords, one bar of music per line,
    explicit breaks and barlines honored; auto-break every bars_per_system
    when the chart uses no explicit breaks."""
    any_explicit = any(b.break_after for s in chart.sections for b in s.bars)
    out = ["  \\set majorSevenSymbol = \\markup \\raise #-0.75 { \"maj7\" }"]
    pos = 0
    for sec in chart.sections:
        for bar in sec.bars:
            tokens = bar.chords
            if len(tokens) == 1 and tokens[0].strip() in ("N.C.", "NC", "nc"):
                out.append("  r" + _duration_token(chart.bar_length))
            else:
                durs = _split_bar(chart.bar_length, len(tokens))
                out.append("  " + " ".join(
                    chord_token(t, d) for t, d in zip(tokens, durs)))
            if bar.barline_after:
                out.append(f"  \\bar {_ly_string(bar.barline_after)}")
            pos += 1
            if bar.break_after or (not any_explicit and pos % chart.bars_per_system == 0):
                out.append("  \\break")
    return "\n".join(out)


def _marks(chart: Chart) -> str:
    """RehearsalMark voice: boxed Hebrew (or plain) section labels at section
    starts, with spacer skips computed from the section bar counts."""
    skip = _duration_token(chart.bar_length)
    lines = []
    for sec in chart.sections:
        if not sec.bars:
            continue
        if sec.label:
            label = _ly_string(sec.label)
            if sec.boxed:
                lines.append("  \\mark \\markup { \\override #'(box-padding . 0.5) "
                             f"\\box {label} }}")
            else:
                lines.append(f"  \\mark \\markup \\bold {label}")
        lines.append(f"  s{skip}*{len(sec.bars)}")
    return "\n".join(lines)


def _slashes(chart: Chart) -> str:
    """Slash voice: one slash per beat (denominator 4) or per eighth (denom 8)."""
    total = sum(len(s.bars) for s in chart.sections)
    if chart.time_den == 4:
        unit = "b4 " * chart.time_num
    elif chart.time_den == 8:
        unit = "b8 " * chart.time_num
    else:
        raise ValueError(f"unsupported time denominator {chart.time_den} for slashes")
    return f"  \\repeat unfold {total} {{ {unit.strip()} }}"


def render_ly(chart: Chart, style_include: str = "roi.ily") -> str:
    return f"""% Generated by chartgen. Do not edit by hand - edit the YAML input instead.
\\version "2.24.4"
\\include "{style_include}"

\\paper {{
  #(set-paper-size "a4")
  tagline = ##f
  system-system-spacing.basic-distance = #17
  system-system-spacing.minimum-distance = #10
}}
\\header {{
  title = {_ly_string(chart.title)}
  composer = {_ly_string(chart.artist)}
}}

chordLine = \\chordmode {{
{_chord_line(chart)}
}}

marks = {{
{_marks(chart)}
}}

slashes = {{
  \\key {chart.key_root} \\{chart.key_mode}
  \\numericTimeSignature
  \\time {chart.time_num}/{chart.time_den}
  \\improvisationOn
  \\override NoteHead.stencil = \\roiSlashStencil
{_slashes(chart)}
}}

\\score {{
  <<
    \\new ChordNames {{ \\chordLine }}
    \\new Staff {{
      \\set Staff.instrumentName = {_ly_string(chart.instrument)}
      <<
        \\marks
        \\new Voice {{ \\clef treble \\slashes }}
      >>
    }}
  >>
  \\layout {{ \\roiLayout }}
}}
"""
